apiVersion: v1
kind: Pod

metadata:
  name: jmeter-demo

spec:
  containers:
    - name: jmeter
      image: 060119698736.dkr.ecr.ap-south-1.amazonaws.com/terraform-demo:v1
      imagePullPolicy: Always

  restartPolicy: Never
