name: Build Run And Push JMeter

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: self-hosted

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Show Current Folder
      run: pwd

    - name: Show Files
      run: dir

    - name: Show Docker Version
      run: docker version

    - name: Build Docker Image
      run: docker build -t jmeter-demo:v1 .

    - name: Verify Image
      run: docker images

    - name: Run JMeter Container
      run: docker run --rm jmeter-demo:v1

    - name: Tag Image For GHCR
      run: docker tag jmeter-demo:v1 ghcr.io/praveennageswaran/jmeter-demo:v1

    - name: Login To GHCR
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u PraveenNageswaran --password-stdin

    - name: Push Image To GHCR
      run: docker push ghcr.io/praveennageswaran/jmeter-demo:v1
