name: Docker Build And Run

on:
  workflow_dispatch:

jobs:
  build-docker:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t jmeter-demo:v1 .

      - name: Verify Docker Image
        run: docker images

  run-container:
    runs-on: self-hosted
    needs: build-docker

    steps:
      - name: Show Docker Images
        run: docker images

      - name: Run JMeter Container
        run: docker run --rm jmeter-demo:v1
